# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37956d3925818ffbf6814eacd891cd2813c99f50367b95d6e3aa305059a743ad2dbd20dc417d8bd0b9aaeb3f1a8274edf771c5f551f714bd2ef10af6ec06d4a2

test:
  secret_key_base: 755dfd79d0692ca602c381a6ca5a42edf627b9692b77228f17e8f95eb242f021439b68133753be6ccd93ecaa56c1a02665924152d0ee2003160ed67fa724c136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
